version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - web
    restart: "on-failure"

  web:
    build: . 
    # command: sh server/run.sh
    command: sh server.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  
