# Generated by Django 3.1.4 on 2021-07-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizes"},
        ),
        migrations.AlterField(
            model_name="mcqquestion",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="option",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="textquestion",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
